[package]
name = "crossmint-megaverse"
version = "0.1.0"
edition = "2021"

[dependencies]
dialoguer = "0.11.0"
figlet-rs = "0.1.5"
reqwest = { version = "0.12.9", features = ["json"] }
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["full"] }
